# Generated by Django 3.2.6 on 2021-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_auto_20210826_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingplatform',
            name='about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
